/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
let fib = [1, 2, 3, 5];
while (fib[fib.length - 1] < 4000000) {
	let lastIndex = fib.length - 1;
	let one = fib[lastIndex - 1];
	let two = fib[lastIndex];
	let next = one + two;
	fib.push(next);
}
let ans = 0;
for (let i = 0; i < fib.length; i++) {
	let cur = fib[i];
	if (cur % 2 == 0) {
		ans += cur;
	}
}
console.log(ans);
